# AirTellecta quarkus Configuration
# App
quarkus.application.name=airtellecta-backend

# HTTP
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:8081,http://localhost:19006
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.exposed-headers=Content-Disposition

# MySQL
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}

# Ddl existente
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Health
quarkus.smallrye-health.ui.enable=true

# Logging
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n
quarkus.log.level=INFO
quarkus.log.category."com.airtellecta".level=DEBUG

# Security
quarkus.http.auth.proactive=true

# Firebase Authentication
# Opción 1 (desarrollo local): ruta directa al archivo JSON
# firebase.credentials.path=airtellecta-1d1ca-firebase-adminsdk-fbsvc-6b25b5a298.json
# Opción 2 (producción): JSON codificado en base64
firebase.credentials.base64=${FIREBASE_CREDENTIALS_BASE64:skip}
